spring.application.name=mon_app
server.port=8082


spring.datasource.url=jdbc:mysql://localhost:3306/service
spring.datasource.username=annete1
spring.datasource.password=annete1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect